### ISSUE TITLE
Learn how to implement the Data Stewardship Initiative from OCDS

### ISSUE THREAD

**Issue by Br-Johnson** [dfo-pacific-science/data-stewardship-unit#79]
Anna has created some notes in Datareef based on recent meeting with Marisa Ramey (OCDS) and South Coast. There are a couple of info sessions coming up put on by Marisa and Declan, one of which Stephen is attending. Please coordinate on this.

**Comment by Br-Johnson** [comment]
@ShaorongDFO @stfinnis @AnnaD-M How is this going? Ideally you are each comfortable guiding staff through filling out the DSI Shortform to get to the point where staff can forward their short forms to Marisa/OCDS. Anna has put some good documentation together in Datareef. I will be attending the training on Nov. 6th, I think Anna will be as well. Shaorong and Stephen I believe know you've both finished it so thanks for that!

Keep in mind that getting stewards identified with the OCDS is one of our key metrics of success!

**Comment by stfinnis** [comment]
Anna made lots of great notes in [DATAREEF](https://086gc.sharepoint.com/sites/Fishery-Assessment_Data_Section-DataStewardshipUnit2/_layouts/OneNote.aspx?id=%2Fsites%2FFishery-Assessment_Data_Section-DataStewardshipUnit2%2FShared%20Documents%2FData%20Stewardship%20Unit%2FDATAREEF&wd=target%28Knowledge%20Base.one%7C263B988A-E92F-4665-9B37-2B0719C21948%2FData%20Stewardship%20Initiative%7C2B550D78-B1A0-4A05-9022-3D506AF29D92%2F%29\)
I just added a few of my own notes. 

After talking to Marisa, it sounds like she wants us to help out with any questions related to the short form, since OCDS is so busy. OCDS will handle the MOU.

@ShaorongDFO, @AnnaD-M, @Br-Johnson, would you like to direct future questions to me about it, as the Regional Data Steward? Or should each person handle any questions sent to them regarding their own projects/data assets?

I currently do not have a plan to actively advertise how we can help support teams with this.

**Comment by AnnaD-M** [comment]
@stfinnis it would be great if you could handle questions for Marisa - do you think you will be having check in meetings with her semi-regularly? Would it be best to have a living document on SharePoint where we could add questions, instead of sending them to you on Teams?

**Comment by Br-Johnson** [comment]
@dfo-pacific-science/data-stewardship-unit I think it would be good for the DSU to route questions about the DSI to Stephen. Stephen, I would then reach out to Declan Embury first rather than Marisa
